# Generated by Django 5.2.12 on 2026-04-20 06:11

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0227_alter_interface_speed_bigint'),
        ('extras', '0134_owner'),
        ('netbox_digital_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('year', models.IntegerField()),
                ('project_name', models.CharField(max_length=300)),
                ('proxy_number', models.CharField(blank=True, max_length=100)),
                ('nomenclature_code', models.CharField(blank=True, max_length=200)),
                ('budget_type', models.CharField(default='capex', max_length=10)),
                ('site_budget', models.CharField(default='cc13', max_length=10)),
                ('unit', models.CharField(default='qty', max_length=10)),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('agreed_budget', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('commercial_proposal_url', models.CharField(blank=True, max_length=500)),
                ('tender_name', models.CharField(blank=True, max_length=300)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_plans', to='netbox_digital_assets.contract')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_plans', to='dcim.device')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_plans', to='netbox_digital_assets.supplier')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['-year', 'project_name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('tender_name', models.CharField(max_length=300)),
                ('status', models.CharField(default='planned', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=200)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='netbox_budget.budgetplan')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='netbox_digital_assets.contract')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='netbox_digital_assets.supplier')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('winner_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tenders', to='netbox_digital_assets.supplier')),
            ],
            options={
                'ordering': ['-budget_plan__year', 'tender_name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
