# Generated by Django 5.2.12 on 2026-04-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplan',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
