# Generated by Django 5.2.12 on 2026-04-21 11:11

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_budget', '0002_budgetplan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('source_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations_made', to='netbox_budget.budgetplan')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('target_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations_received', to='netbox_budget.budgetplan')),
            ],
            options={
                'ordering': ['-date'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
