# Generated by Django 5.2.12 on 2026-04-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_budget', '0003_budgetmerge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['tender_name']},
        ),
        migrations.RemoveField(
            model_name='tender',
            name='budget_plan',
        ),
        migrations.AddField(
            model_name='tender',
            name='budget_plans',
            field=models.ManyToManyField(blank=True, related_name='tenders', to='netbox_budget.budgetplan'),
        ),
    ]
