# Generated by Django 5.2.12 on 2026-04-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_budget', '0004_alter_tender_options_remove_tender_budget_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='contract_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
