# Generated by Django 5.2.12 on 2026-04-29 09:17

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_budget', '0005_tender_contract_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetplan',
            name='nomenclature_code',
        ),
        migrations.CreateModel(
            name='ItemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=300)),
                ('short_name_kaz', models.CharField(blank=True, max_length=300)),
                ('specification_kaz', models.TextField(blank=True)),
                ('short_name_rus', models.CharField(blank=True, max_length=300)),
                ('specification_rus', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='item_codes/')),
                ('cancelled_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_plans', to='netbox_budget.itemcode'),
        ),
    ]
