# Generated by Django 5.2.12 on 2026-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_budget', '0006_remove_budgetplan_nomenclature_code_itemcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcode',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='itemcode',
            name='short_name_kaz',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='itemcode',
            name='short_name_rus',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
