# Generated by Django 5.2.12 on 2026-06-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_budget', '0007_alter_itemcode_name_alter_itemcode_short_name_kaz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplan',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
