# Generated by Django 5.2.12 on 2026-06-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_budget', '0008_budgetplan_comments_tender_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetplan',
            name='item_code',
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='item_code',
            field=models.ManyToManyField(blank=True, related_name='budget_plans', to='netbox_budget.itemcode'),
        ),
    ]
